export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const GET_BOOK_LIST = 'GET_BOOK_LIST';
export const GET_BOOK_LIST_SUCCEEDED = 'GET_BOOK_LIST_SUCCEEDED';
export const GET_BOOK_LIST_FAILED = 'GET_BOOK_LIST_FAILED';

export const GET_SEARCH_BOOK_LIST = 'GET_SEARCH_BOOK_LIST';
export const GET_SEARCH_BOOK_LIST_SUCCEEDED = 'GET_SEARCH_BOOK_LIST_SUCCEEDED';
export const GET_SEARCH_BOOK_LIST_FAILED = 'GET_SEARCH_BOOK_LIST_FAILED';